export const UserData = [
  {
    id:1,
    name: "Mohammad Sahil",
    username: "m_sahillll",
    profile: require("../assets/data/Profile.png"),

    story: {
      time: 10,
      image: require("../assets/data/Post1.png"),
    },
    post: {
      time: "09:00:00",
      date: "01/05/2023",
      image: require("../assets/data/Post1.png"),
      caption: "Hi Everyone, Elon musk is here",
      like: 1200,
      comment: 643,
      share: 238,
    },
  },
  {
    id: 2,
    name: "Nikhil Sharma",
    username: "nikkkhil",
    profile: require("../assets/data/nikhildp.jpg"),
    story: {
      time: 10,
      image: require("../assets/data/elonstory.png"),
    },
     post: {
      time: "09:00:00",
      date: "01/05/2023",
      image: require("../assets/data/nikhilpost.jpg"),
      caption: "You me and BMW. Jodi made in heaven .",
      like: 583,
      comment: 234,
      share: 344,
    }, 
  },
  {
    id: 3,
    name: "Bhuvan Bam",
    username: "bhuvan",
    profile: require("../assets/data/bhuvandp.jpg"),
    story: {
      time: 8,
      image: require("../assets/data/harshs.png"),
    },
     post: {
      time: "04:00 PM",
      date: "08/04/2023",
      image: require("../assets/data/bhuvanpost.jpg"),
      caption: "MEREKO EK VARDAAN HAI 🥵",
      like: 3350,
      comment: 378,
      share: 288,
    },
  },
  {
    id: 4,
    name: "Narendra Modi",
    username: "narendramodi",
    profile: require("../assets/data/modidp.png"),
    story: {
      time: 15,
      image: require("../assets/data/modip.png"),
    },
    post: {
      time: "07:00 AM",
      date: "12/05/2023",
      image: require("../assets/data/narendramodipost.jpg"),
      caption: "2000 ke note band",
      like: 380,
      comment: 230,
      share: 30,
    }, 
  },
  {
    id: 5,
    name: "Ashneer Grover",
    username: "ashneer",
    profile: require("../assets/data/ashneerdp.jpg"),
    story: {
      time: 13,
      image: require("../assets/data/sonams.png"),
    },
     post: {
      time: "07:00 AM",
      date: "12/05/2023",
      image: require("../assets/data/ashneerpost.jpg"),
      caption: "Wish you all a very Happy New Year 2025!! ",
      like: 990,
      comment: 750,
      share: 303,
    }, 
  },
  {
    id: 6,
    name: "Abhishek Upmanyu",
    username: "muskelon",
    profile: require("../assets/data/abhishekdp.jpg"),
    story: {
      time: 10,
      image: require("../assets/data/elonstory.png"),
    },
     post: {
      time: "09:00:00",
      date: "01/05/2023",
      image: require("../assets/data/abhishekpost.jpg"),
      caption: "Hi Everyone, Elon musk is here",
      like: 583,
      comment: 234,
      share: 344,
    }, 
  },
];
